# Use the official python:3 image as the base
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the Flask application files to the container
COPY admin_web_framework/ /app/

# Install Flask and any other required dependencies
RUN pip install Flask

# Expose the port that Flask will run on
EXPOSE 5002

# Command to start the admin Flask web framework
CMD ["python", "app.py"]
