# Use the official python:3 image as the base
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the Flask application files to the container
COPY web_framework/ /app/
COPY web_framework/requirements.txt /app/

# Install required Python packages from requirements.txt
RUN pip install -r requirements.txt

# Expose the port that Flask will run on
EXPOSE 5003

# Command to start the Flask web framework
CMD ["python", "app.py"]
